/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportalbaran;

import entidades.CabAlbaran;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import listasdatos.ListaCabAlbaran;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import listasdatos.ListaDetAlbaran;
import reports.Informe;

/**
 *
 * @author sicra
 */
public class VentAlbaran extends javax.swing.JFrame implements Runnable {
    
    private ArrayList listaCabeceras;
    private ArrayList listaLineas;
    private int indice;
    private int tamanyoLista;
    private ModeloTablaDetalle modeloTabla;
    private Informe informeDetAlb;
    
    // para el reloj
    private String hora, min, sec, dia, mes, anyo, ampm;
    private Calendar calendario;
    private Thread hilo;

    /**
     * Creates new form VentAlbaran
     */
    public VentAlbaran() throws SQLException, ClassNotFoundException {
        initComponents();
        
        indice = 0;
        tamanyoLista = 0;
        informeDetAlb = new Informe();
        
        this.obtenerDatos();
        
        bt_primero.setEnabled(false);
        bt_anterior.setEnabled(false);
        
        hilo = new Thread(this);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jToolBar_navegacion = new javax.swing.JToolBar();
        bt_primero = new javax.swing.JButton();
        bt_anterior = new javax.swing.JButton();
        bt_siguiente = new javax.swing.JButton();
        bt_ultimo = new javax.swing.JButton();
        jToolBar_crearInforme = new javax.swing.JToolBar();
        bt_genInforme = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_numAlbaran = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tf_fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tf_idCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_nomCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_descComercial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_nomEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_idEmpleado = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detalleAlabaran = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        tf_totalBruto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        tf_importeDescComer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        tf_baseImponible = new javax.swing.JTextField();
        lb_reloj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alabaranes");
        setIconImage(getIconImage());
        setResizable(false);

        jToolBar_navegacion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jToolBar_navegacion.setFloatable(false);
        jToolBar_navegacion.setRollover(true);
        jToolBar_navegacion.setMargin(new java.awt.Insets(5, 5, 10, 0));

        bt_primero.setText("Primero");
        bt_primero.setToolTipText("Va al primer albaran de la lista");
        bt_primero.setFocusable(false);
        bt_primero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_primero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_primeroActionPerformed(evt);
            }
        });
        jToolBar_navegacion.add(bt_primero);

        bt_anterior.setText("Anterior");
        bt_anterior.setToolTipText("Albaran anterior");
        bt_anterior.setFocusable(false);
        bt_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_anterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anteriorActionPerformed(evt);
            }
        });
        jToolBar_navegacion.add(bt_anterior);

        bt_siguiente.setText("Siguiente");
        bt_siguiente.setToolTipText("Albaran siguiente");
        bt_siguiente.setFocusable(false);
        bt_siguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_siguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_siguienteActionPerformed(evt);
            }
        });
        jToolBar_navegacion.add(bt_siguiente);

        bt_ultimo.setText("Último");
        bt_ultimo.setToolTipText("Va al último albaran de la lista");
        bt_ultimo.setFocusable(false);
        bt_ultimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_ultimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ultimoActionPerformed(evt);
            }
        });
        jToolBar_navegacion.add(bt_ultimo);

        jToolBar_crearInforme.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jToolBar_crearInforme.setFloatable(false);
        jToolBar_crearInforme.setRollover(true);
        jToolBar_crearInforme.setMargin(new java.awt.Insets(5, 0, 10, 5));

        bt_genInforme.setText("Imprimir Informe");
        bt_genInforme.setToolTipText("Visualiza un informe para imprimirlo o guardarlo");
        bt_genInforme.setFocusable(false);
        bt_genInforme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_genInforme.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_genInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_genInformeActionPerformed(evt);
            }
        });
        jToolBar_crearInforme.add(bt_genInforme);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setText("Albarán número:");
        jLabel1.setToolTipText("Numero de albaran");

        tf_numAlbaran.setEditable(false);
        tf_numAlbaran.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        tf_fecha.setEditable(false);
        tf_fecha.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel2.setText("Fecha:");
        jLabel2.setToolTipText("Fecha en la que se genró el albaran");

        jLabel3.setText("Datos del cliente");

        jLabel4.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel4.setText("Número:");
        jLabel4.setToolTipText("Identificadro de cliente");

        tf_idCliente.setEditable(false);
        tf_idCliente.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel5.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel5.setText("Nombre:");
        jLabel5.setToolTipText("Nombre del cliente");

        tf_nomCliente.setEditable(false);
        tf_nomCliente.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel6.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel6.setText("Descuento Comercial:");
        jLabel6.setToolTipText("Descuento aplicable sobre el total");

        tf_descComercial.setEditable(false);
        tf_descComercial.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel7.setText("Atendido por:");
        jLabel7.setToolTipText("Empleado que atendio al al cliente");

        tf_nomEmpleado.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel8.setText("# Empleado:");
        jLabel8.setToolTipText("Numero de empleado");

        tf_idEmpleado.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_numAlbaran, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_descComercial, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(tf_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(84, 84, 84)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_numAlbaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(tf_nomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_descComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tf_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_detalleAlabaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_detalleAlabaran.setToolTipText("Detalle del albaran");
        jScrollPane1.setViewportView(table_detalleAlabaran);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Total Bruto");
        jLabel9.setToolTipText("Total Bruto: la suma de todos los imortes");

        tf_totalBruto.setEditable(false);
        tf_totalBruto.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel10.setText("* Precios sin IVA");

        tf_importeDescComer.setEditable(false);
        tf_importeDescComer.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Descuento Comercial");
        jLabel11.setToolTipText("Importe a descontar");

        jSeparator7.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Base Imponible *");
        jLabel12.setToolTipText("Base imponible: Total bruto menos el descuento comercial");

        tf_baseImponible.setEditable(false);
        tf_baseImponible.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        lb_reloj.setText("jLabel13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar_navegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar_crearInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_totalBruto, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(tf_importeDescComer)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_reloj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_baseImponible, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar_navegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar_crearInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_totalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_importeDescComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_baseImponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(lb_reloj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_primeroActionPerformed
        // TODO add your handling code here:
        indice = 0;
        this.mostrarRegistro();
        bt_primero.setEnabled(false);
        bt_anterior.setEnabled(false);
        bt_ultimo.setEnabled(true);
        bt_siguiente.setEnabled(true);
    }//GEN-LAST:event_bt_primeroActionPerformed

    private void bt_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anteriorActionPerformed
        // TODO add your handling code here:
        if (indice > 0) {
            indice --;
            this.mostrarRegistro();
            bt_ultimo.setEnabled(true);
            bt_siguiente.setEnabled(true);
        }
        
        if (indice == 0) {
            bt_primero.setEnabled(false);
            bt_anterior.setEnabled(false);
        }
    }//GEN-LAST:event_bt_anteriorActionPerformed

    private void bt_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_siguienteActionPerformed
        // TODO add your handling code here:
        if (indice + 1 < tamanyoLista) {
            indice++;
            this.mostrarRegistro();
            bt_primero.setEnabled(true);
            bt_anterior.setEnabled(true);
        }
        
        if (indice + 1 == tamanyoLista) {
            bt_ultimo.setEnabled(false);
            bt_siguiente.setEnabled(false);
        }
    }//GEN-LAST:event_bt_siguienteActionPerformed

    private void bt_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ultimoActionPerformed
        // TODO add your handling code here:
        indice = tamanyoLista - 1;
        this.mostrarRegistro();
        bt_ultimo.setEnabled(false);
        bt_siguiente.setEnabled(false);
        bt_primero.setEnabled(true);
        bt_anterior.setEnabled(true);
    }//GEN-LAST:event_bt_ultimoActionPerformed

    private void bt_genInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_genInformeActionPerformed
        // TODO add your handling code here:
        String[] valores = {"Windows", "Linux"};
        String SO = (String)JOptionPane.showInputDialog(this, "Elija su SO:", "ELija SO", JOptionPane.QUESTION_MESSAGE, null, valores, valores[0]);
        if (SO != null) {
            informeDetAlb.ejecutarInforme(Integer.parseInt(tf_numAlbaran.getText()), SO);
        }
        
    }//GEN-LAST:event_bt_genInformeActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_anterior;
    private javax.swing.JButton bt_genInforme;
    private javax.swing.JButton bt_primero;
    private javax.swing.JButton bt_siguiente;
    private javax.swing.JButton bt_ultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar jToolBar_crearInforme;
    private javax.swing.JToolBar jToolBar_navegacion;
    private javax.swing.JLabel lb_reloj;
    private javax.swing.JTable table_detalleAlabaran;
    private javax.swing.JTextField tf_baseImponible;
    private javax.swing.JTextField tf_descComercial;
    private javax.swing.JTextField tf_fecha;
    private javax.swing.JTextField tf_idCliente;
    private javax.swing.JTextField tf_idEmpleado;
    private javax.swing.JTextField tf_importeDescComer;
    private javax.swing.JTextField tf_nomCliente;
    private javax.swing.JTextField tf_nomEmpleado;
    private javax.swing.JTextField tf_numAlbaran;
    private javax.swing.JTextField tf_totalBruto;
    // End of variables declaration//GEN-END:variables

    private void obtenerDatos() {
        try {
            // Cabeceras
            listaCabeceras = new ListaCabAlbaran().todasLasCabeceras();
            if (listaCabeceras.isEmpty()) {
               JOptionPane.showMessageDialog(
                        this,
                        "No hay Albaranes registrados\nen la BBDD.",
                        "Error: Sin datos",
                        JOptionPane.ERROR_MESSAGE
                ); 
            } else {
                this.mostrarRegistro();
            }
            
        } catch (Exception ex) {
            System.out.println("Error importando datos a las listas.");
        }
    }

    private void mostrarRegistro() {
        tamanyoLista = listaCabeceras.size();
        CabAlbaran cabecera = null; // para evitar problemas cuando refrescque al cambiar
        cabecera = (CabAlbaran) listaCabeceras.get(indice);
        // rellenamos tfs
        tf_numAlbaran.setText(String.valueOf(cabecera.getIdAlbaran()));
        tf_fecha.setText(this.parseDateToString(cabecera.getFecha()));
        tf_idCliente.setText(String.valueOf(cabecera.getCliente_id()));
        tf_nomCliente.setText(cabecera.getCliente_nom());
        tf_nomEmpleado.setText(cabecera.getEmpleado_nom());
        tf_idEmpleado.setText(String.valueOf(cabecera.getEmpleado_id()));
        tf_descComercial.setText(String.valueOf(cabecera.getDtoComercial())+"%");
        
        try {
            // Cargamos las líneas del albaran mostrado
            listaLineas = new ListaDetAlbaran().todasLasLineasPorAlbId(cabecera.getIdAlbaran());
            modeloTabla = new ModeloTablaDetalle(listaLineas);
            table_detalleAlabaran.setModel(modeloTabla);
            
            this.calculaTotales(cabecera.getDtoComercial());
            
        } catch (Exception ex) {
            System.out.println("Error en la carga de líneas del albarán "+cabecera.getIdAlbaran());
        }
        
        
    }
    
    private String parseDateToString(Date fecha) {
        return new SimpleDateFormat("dd/MM/yyyy").format(fecha);
    }
    
    private void calculaTotales (int descComercial) {
        
        double bruto = 0;
        double descuento = 0;
        double porcDesc = (double)descComercial / 100;
        DecimalFormat df = new DecimalFormat("#.##");
        
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            bruto += Double.valueOf(modeloTabla.getValueAt(i, 5).toString());
        }
        
        tf_totalBruto.setText(df.format(bruto) + "€");
        
        System.out.print(descComercial + " " + descComercial / 100);
        
        descuento = bruto * porcDesc;
        
        tf_importeDescComer.setText(df.format(descuento) + "€");
        
        tf_baseImponible.setText(df.format(bruto - descuento) + "€");
    }

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == hilo) {
            calcula();
            lb_reloj.setText(hora+":"+min+":"+sec);
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
            
        }
    }
    
    public void calcula () {
        Calendar cal = new GregorianCalendar();
        Date fechaHoraActual = new Date();
            
        cal.setTime(fechaHoraActual);
        ampm = cal.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        if(ampm.equals("PM")){
        int h = cal.get(Calendar.HOUR_OF_DAY)-12;
        hora = h>9?""+h:"0"+h;
        }else{
        hora = cal.get(Calendar.HOUR_OF_DAY)>9?""+cal.get(Calendar.HOUR_OF_DAY):"0"+cal.get(Calendar.HOUR_OF_DAY); }
        min = cal.get(Calendar.MINUTE)>9?""+cal.get(Calendar.MINUTE):"0"+cal.get(Calendar.MINUTE);
        sec = cal.get(Calendar.SECOND)>9?""+cal.get(Calendar.SECOND):"0"+cal.get(Calendar.SECOND);
    }
}
